Accessibility corrections for Reports AB#46056, AB#46083, AB#45387
HistoricEngland/arches-her pull request #235
Opened 2022-10-05 10:12 UTC by csmith-he

AB#46056 
AB#46083
AB#45387

- Keyboard accessibility added to Geometry Metatdata in Location scene
- Keyboard accessibility added to edit/delete buttons in reports
- Contrast errors fixed in all reports
- Contrast errors fixed in all details reports

2022-11-01 12:56 UTC, csmith-he commented
@phudson-he - Again, could you quickly act as my Dev peer reviewer for this, please?

2022-11-01 15:35 UTC, phudson-he commented on arches_her/templates/views/components/reports/bibliographic-source.htm
> +                                                        <a tabindex="0" data-bind="click: function() {$parent.editTile(tileid, $parent.cards.sourceNames)}" onkeyup="if(event.which == 13 || event.keyC
Need to add some href's

2022-11-01 15:49 UTC, csmith-he commented on arches_her/templates/views/components/reports/bibliographic-source.htm
> +                                                        <a tabindex="0" data-bind="click: function() {$parent.editTile(tileid, $parent.cards.sourceNames)}" onkeyup="if(event.which == 13 || event.keyC
@phudson-he Requested changes made - I think I caught them all

2022-11-02 11:54 UTC, phudson-he approved these changes
All looks good

2022-11-02 12:03 UTC, csmith-he commented
@Rehaan-Arif  - this is now ready for Release Candidate testing

2022-11-03 16:21 UTC, Rehaan-Arif approved these changes
Testing complete on these tickets

2022-11-04 09:33 UTC, aj-he requested changes
Can you sort the console log issue in the template and then we're good to go.

2022-11-04 09:33 UTC, aj-he commented on arches_her/templates/views/components/reports/scenes/resources.htm
> +                                    <div data-bind="text: console.log($parent.cards.translation)"></div>
@csmith-he there should not be a console log in the template right?

2022-11-07 11:29 UTC, csmith-he commented on arches_her/templates/views/components/reports/scenes/resources.htm
> +                                    <div data-bind="text: console.log($parent.cards.translation)"></div>
@aj-he - Correct.  I've removed it now

2022-11-07 13:24 UTC, aj-he commented on arches_her/templates/views/components/reports/scenes/resources.htm
> +                                    <div data-bind="text: console.log($parent.cards.translation)"></div>
looks good now

2022-11-07 13:25 UTC, merged