Change associated consultations message depending on permissions AB#50806
HistoricEngland/arches-her pull request #239
Opened 2022-10-07 09:46 UTC by RobOatesHistoricEngland

AB#50806

2022-10-14 07:48 UTC, aj-he requested changes
see reinstatiation comment

2022-10-14 07:48 UTC, aj-he commented on arches_her/media/js/views/components/reports/scenes/resources.js
> +                    self.consultations_message = ko.observable('No consultations for this resource');
do you need to re-instantiate the `consultations_message` observable in lines 113 and 115 or can you just change the value, e.g. `self.consultations_message('You do not have permission to view this data');`??

2022-11-03 09:32 UTC, csmith-he approved these changes
Looks good to me

2022-11-22 11:12 UTC, aj-he approved these changes

2022-11-24 13:03 UTC, Rehaan-Arif reviewed
This has failed testing

2023-03-01 15:33 UTC, aj-he commented
@RobOatesHistoricEngland and @csmith-he is this still current?

2023-03-01 15:39 UTC, csmith-he commented
@aj-he @RobOatesHistoricEngland I think my work on the Consultations message superseded this.  Rob, am I correct in thinking that?

2023-03-01 16:06 UTC, RobOatesHistoricEngland commented
@aj-he @csmith-he I also think that Chantelle's work superseded my PR.

2023-03-02 09:31 UTC, aj-he commented
OK, I'll close this then

2023-03-02 09:31 UTC, closed without merging