R112 merge in 52982 branded password reset pages
HistoricEngland/arches-her pull request #271
Opened 2022-12-22 11:25 UTC by phudson-he

To include the branding changes to all the password reset page, matching the branded landing and login pages

2022-12-22 11:54 UTC, RobOatesHistoricEngland requested changes

2022-12-22 11:54 UTC, RobOatesHistoricEngland commented on arches_her/templates/registration/password_reset_complete.html
> +            <p>Your password has been set.  You may go ahead and <a href="{% url 'auth' %}">log in now</a>.</p>
That anchor link looks a little odd to me, especially when it's proceeded by `log in now` with no spacing. Is this right?

2022-12-22 11:54 UTC, RobOatesHistoricEngland commented on arches_her/templates/registration/password_reset_confirm.html
> +				<p>The password reset link was invalid, possibly because it has already been used.  Please <a href="{% url 'password_reset' %}">request a new password reset</a>.</p>
Same comment here about the anchor link and the text immediately following it.

2022-12-22 12:28 UTC, phudson-he commented on arches_her/templates/registration/password_reset_complete.html
> +            <p>Your password has been set.  You may go ahead and <a href="{% url 'auth' %}">log in now</a>.</p>
Renders fine...
![image](https://user-images.githubusercontent.com/52997281/209134496-3b48a4e8-7d5b-421d-98d3-19491bb075f6.png)

2022-12-22 12:29 UTC, phudson-he commented on arches_her/templates/registration/password_reset_confirm.html
> +				<p>The password reset link was invalid, possibly because it has already been used.  Please <a href="{% url 'password_reset' %}">request a new password reset</a>.</p>
Also renders fine...
![image](https://user-images.githubusercontent.com/52997281/209134683-de70b52f-0a04-42dc-868b-63ec71aed92d.png)

2022-12-22 15:11 UTC, RobOatesHistoricEngland approved these changes
Looks good

2023-01-06 12:52 UTC, Rehaan-Arif approved these changes
tested successfully

2023-01-10 14:14 UTC, phudson-he commented on arches_her/templates/registration/password_reset_email.html
> +{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}
Line removed

2023-01-10 14:14 UTC, phudson-he commented on arches_her/templates/change_password.htm
> +                                    <div class="error-message" data-bind="text:invalidPassword"></div>
Added aria-live attribute, errors now read out by screen reader, checked with NVDA

2023-01-10 14:14 UTC, phudson-he commented on arches_her/templates/change_password.htm
> +                                        <div data-bind="text: $data" class="error-message"></div>
Added aria-live attribute, errors now read out by screen reader, checked with NVDA

2023-01-10 15:35 UTC, aj-he approved these changes
Looks good to me.

2023-01-10 15:35 UTC, merged